// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             int32              `json:"id"`
	Email          string             `json:"email"`
	Name           pgtype.Text        `json:"name"`
	HashedPassword string             `json:"hashed_password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LastActiveAt   pgtype.Timestamptz `json:"last_active_at"`
}

type UserToken struct {
	ID                    int32              `json:"id"`
	UserID                int32              `json:"user_id"`
	AccessToken           string             `json:"access_token"`
	RefreshToken          string             `json:"refresh_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	IsActive              bool               `json:"is_active"`
}
