// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO user_tokens (user_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, created_at, is_active
`

type CreateUserTokenParams struct {
	UserID                int32              `json:"user_id"`
	AccessToken           string             `json:"access_token"`
	RefreshToken          string             `json:"refresh_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error) {
	row := q.db.QueryRow(ctx, createUserToken,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
	)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const deactivateAllUserTokens = `-- name: DeactivateAllUserTokens :exec
UPDATE user_tokens SET is_active = FALSE WHERE user_id = $1
`

func (q *Queries) DeactivateAllUserTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deactivateAllUserTokens, userID)
	return err
}

const deactivateToken = `-- name: DeactivateToken :exec
UPDATE user_tokens SET is_active = FALSE WHERE access_token = $1
`

func (q *Queries) DeactivateToken(ctx context.Context, accessToken string) error {
	_, err := q.db.Exec(ctx, deactivateToken, accessToken)
	return err
}

const getUserTokenByAccessToken = `-- name: GetUserTokenByAccessToken :one
SELECT id, user_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, created_at, is_active FROM user_tokens
WHERE access_token = $1 AND is_active = TRUE
`

func (q *Queries) GetUserTokenByAccessToken(ctx context.Context, accessToken string) (UserToken, error) {
	row := q.db.QueryRow(ctx, getUserTokenByAccessToken, accessToken)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const getUserTokenByRefreshToken = `-- name: GetUserTokenByRefreshToken :one
SELECT id, user_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, created_at, is_active FROM user_tokens
WHERE refresh_token = $1 AND is_active = TRUE
`

func (q *Queries) GetUserTokenByRefreshToken(ctx context.Context, refreshToken string) (UserToken, error) {
	row := q.db.QueryRow(ctx, getUserTokenByRefreshToken, refreshToken)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}
