// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, hashed_password, created_at, updated_at, last_active_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, hashed_password, created_at, updated_at, last_active_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO users (email, name, hashed_password)
VALUES ($1, $2, $3)
RETURNING id, email, name, hashed_password, created_at, updated_at, last_active_at
`

type RegisterUserParams struct {
	Email          string      `json:"email"`
	Name           pgtype.Text `json:"name"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRow(ctx, registerUser, arg.Email, arg.Name, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name       = COALESCE($2, name),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, hashed_password, created_at, updated_at, last_active_at
`

type UpdateUserParams struct {
	ID   int32       `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const updateUserLastActive = `-- name: UpdateUserLastActive :one
UPDATE users
SET last_active_at = $2,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, email, name, hashed_password, created_at, updated_at, last_active_at
`

type UpdateUserLastActiveParams struct {
	ID           int32              `json:"id"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) UpdateUserLastActive(ctx context.Context, arg UpdateUserLastActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLastActive, arg.ID, arg.LastActiveAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}
